Interactive Multimedia: CountDownTimer Class Reference
CountDownTimer Class Reference
Public Member Functions
int GetTotalSeconds ()
void ResetTimer (int seconds)
int GetSecondsRemaining ()
float GetProportionTimeRemaining ()
Public Attributes
Texture2D time0
Texture2D time1
Texture2D time2
Texture2D time3
Texture2D time4
Texture2D time5
Texture2D time6
Texture2D time7
Texture2D time8
Texture2D time9
Texture2D time10
AudioClip timeAlmostUp
int countdownTimerDuration = 10
Private Member Functions
void Start ()
void OnGUI ()
void DisplayTimeBar (int i)
Texture2D getImage (int i)
bool GetPercent (int i, int Percentage)
Private Attributes
int labelY = Screen.width / 2 - 200
int labelX = Screen.height - 50
int labelWidth = 400
int labelHeight = 50
bool timeUpSoundPlaying = false
float countdownTimerStartTime
Detailed Description
Definition at line 6 of file CountDownTimer.cs.
Member Function Documentation
void CountDownTimer.DisplayTimeBar (int i) [private]
This method display the remaining time bar
Definition at line 46 of file CountDownTimer.cs.
References getImage(), labelHeight, labelWidth, labelX, and labelY.
Referenced by OnGUI().
{
                GUI.Label (new Rect (labelY, labelX, labelWidth, labelHeight), getImage(i));
        }
Texture2D CountDownTimer.getImage (int i) [private]
This method return the value of the Texture2D (image) depending on the persent of remaining time
Parameters:
i int value of remaining time
Returns:
Texture2D image of remaining time
Definition at line 54 of file CountDownTimer.cs.
References GetPercent(), time0, time1, time10, time2, time3, time4, time5, time6, time7, time8, and time9.
Referenced by DisplayTimeBar().
{
                if( GetPercent(i,0)){return time0;}
                else if(GetPercent(i,10)){return time1;}
                else if(GetPercent(i,20)){ return time2;}
                else if(GetPercent(i,30)){ return time3;}
                else if(GetPercent(i,40)){ return time4;}
                else if(GetPercent(i,50)){ return time5;}
                else if(GetPercent(i,60)){ return time6;}
                else if(GetPercent(i,70)){ return time7;}
                else if(GetPercent(i,80)){ return time8;}
                else if(GetPercent(i,90)){ return time9;}
                else if(GetPercent(i,100)){ return time10;}
                else{return null;}
        }
bool CountDownTimer.GetPercent (int i, int Percentage) [private]
This method calculate the percentage of remaining time
Parameters:
i remaining time
Percentage value of the percent (10%, 40%...)
Returns:
bool (true: if Percentage value is equal to the remaining time)
Definition at line 73 of file CountDownTimer.cs.
References countdownTimerDuration.
Referenced by getImage().
{
                int XYZ = (i * 100) / countdownTimerDuration;
                if(XYZ <= Percentage ){
                        return true;
                }else{
                        return false;
                }
        }
float CountDownTimer.GetProportionTimeRemaining ()
return remaining seconds float value
Definition at line 100 of file CountDownTimer.cs.
References GetSecondsRemaining(), and GetTotalSeconds().
        {
                float proportionLeft = (float)GetSecondsRemaining() / (float)GetTotalSeconds();
                return proportionLeft;
        }
int CountDownTimer.GetSecondsRemaining ()
return remaining seconds
Definition at line 93 of file CountDownTimer.cs.
References countdownTimerDuration, and countdownTimerStartTime.
Referenced by GetProportionTimeRemaining(), and OnGUI().
        {
                int elapsedSeconds = (int)(Time.time - countdownTimerStartTime);
                int secondsLeft = (countdownTimerDuration - elapsedSeconds);
                return secondsLeft;
        }
int CountDownTimer.GetTotalSeconds ()
return total seconds
Definition at line 82 of file CountDownTimer.cs.
References countdownTimerDuration.
Referenced by GetProportionTimeRemaining(), and RolloverButton.OnMouseUp().
        {
                return countdownTimerDuration;
        }
void CountDownTimer.OnGUI () [private]
on every frame refreshed
Definition at line 33 of file CountDownTimer.cs.
References DisplayTimeBar(), GetSecondsRemaining(), timeAlmostUp, and timeUpSoundPlaying.
{
                DisplayTimeBar (GetSecondsRemaining ());
                if(GetSecondsRemaining () == 0){
                        int Game_Over_Level = 2;
                        Application.LoadLevel(Game_Over_Level);
                }
                if(GetSecondsRemaining () <= 5 && !timeUpSoundPlaying){
                        audio.PlayOneShot(timeAlmostUp);
                        timeUpSoundPlaying = true;
                }
        }
void CountDownTimer.ResetTimer (int seconds)
This method is used to reset the value of the timer in case of level win!
Definition at line 87 of file CountDownTimer.cs.
References countdownTimerDuration, and countdownTimerStartTime.
Referenced by PlayerGUI.DisplayCurrentComponents(), RolloverButton.OnMouseUp(), and Start().
        {
                countdownTimerStartTime = Time.time;
                countdownTimerDuration = seconds;
        }
void CountDownTimer.Start () [private]
when the script is loaded (on level start)
Definition at line 29 of file CountDownTimer.cs.
References countdownTimerDuration, and ResetTimer().
{
                ResetTimer(countdownTimerDuration);
        }
Member Data Documentation
int CountDownTimer.countdownTimerDuration = 10
Definition at line 27 of file CountDownTimer.cs.
Referenced by GetPercent(), GetSecondsRemaining(), GetTotalSeconds(), ResetTimer(), and Start().
float CountDownTimer.countdownTimerStartTime [private]
Definition at line 26 of file CountDownTimer.cs.
Referenced by GetSecondsRemaining(), and ResetTimer().
int CountDownTimer.labelHeight = 50 [private]
Definition at line 23 of file CountDownTimer.cs.
Referenced by DisplayTimeBar().
int CountDownTimer.labelWidth = 400 [private]
Definition at line 22 of file CountDownTimer.cs.
Referenced by DisplayTimeBar().
int CountDownTimer.labelX = Screen.height - 50 [private]
Definition at line 21 of file CountDownTimer.cs.
Referenced by DisplayTimeBar().
int CountDownTimer.labelY = Screen.width / 2 - 200 [private]
Definition at line 20 of file CountDownTimer.cs.
Referenced by DisplayTimeBar().
Texture2D CountDownTimer.time0
Definition at line 8 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time1
Definition at line 9 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time10
Definition at line 18 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time2
Definition at line 10 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time3
Definition at line 11 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time4
Definition at line 12 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time5
Definition at line 13 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time6
Definition at line 14 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time7
Definition at line 15 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time8
Definition at line 16 of file CountDownTimer.cs.
Referenced by getImage().
Texture2D CountDownTimer.time9
Definition at line 17 of file CountDownTimer.cs.
Referenced by getImage().
AudioClip CountDownTimer.timeAlmostUp
Definition at line 19 of file CountDownTimer.cs.
Referenced by OnGUI().
bool CountDownTimer.timeUpSoundPlaying = false [private]
Definition at line 24 of file CountDownTimer.cs.
Referenced by OnGUI().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/CountDownTimer.cs