Interactive Multimedia: PlayerGUI Class Reference
PlayerGUI Class Reference
Public Member Functions
bool IsCarryingKey ()
bool IsCarryingFlashLight ()
Public Attributes
GameLogic gameLogic
CountDownTimer CDTimer
GameObject spotlightGO
GameObject numbersGO
GameObject operatorsGO
Texture2D flashLight
AudioClip numberSound
AudioClip operatorSound
AudioClip calculateSound
AudioClip flashLightOn
AudioClip errorSound
AudioClip winSound
GUIText popup
Private Member Functions
void OnGUI ()
void DisplayCurrentComponents ()
bool IsWinner ()
void ComponentsToDisplay (string s, int i)
IEnumerator WaitSomeTime ()
void Calculate ()
void OnTriggerEnter (Collider c)
void IncreaseSequence ()
int GetValueInt (string s)
void SetOperator (string s)
string GetOperatorValue ()
bool IsOperator (string s)
bool IsNumber (string s)
void TurnFlashLightOn ()
void ShowNumbers ()
void ShowOperators ()
bool IsLoadedLevel (int i)
Private Attributes
int sequence = 1
bool isFirstNum
bool isSecondNum
bool isOperator
bool carryingFlashLight = false
int result
int firstNumberValue
int secondNumberValue
string operatorValue
int labelTargetY = Screen.width / 2 - 100
int labelTargetX = Screen.height - 100
int labelTargetWidth = 400
int labelTargetHeight = 100
Detailed Description
Definition at line 13 of file PlayerGUI.cs.
Member Function Documentation
void PlayerGUI.Calculate () [private]
This method performs calculation using (firstnumber, operator, secondnumber)
Definition at line 148 of file PlayerGUI.cs.
References firstNumberValue, GetOperatorValue(), isOperator, isSecondNum, result, secondNumberValue, and sequence.
Referenced by WaitSomeTime().
{
                int firstNum = firstNumberValue;
                int secondNum = secondNumberValue;
                string currentOperator = GetOperatorValue ();
                     if(currentOperator == "X"){  result =firstNum * secondNum;  }
                else if(currentOperator == "+"){  result =firstNum + secondNum;  }
                else if(currentOperator == "-"){  result =firstNum - secondNum;  }
                isSecondNum = false;
                isOperator = false;
                currentOperator = null;
                firstNumberValue = result;
                sequence = 2;
        }
void PlayerGUI.ComponentsToDisplay (string s, int i) [private]
This method determin which component to display on the screen
Parameters:
s String the tag value of the object picked up
i Int value of
See also:
sequence
GetValueInt()
setOperator()
WaitSomeTime()
Definition at line 117 of file PlayerGUI.cs.
References calculateSound, firstNumberValue, GetValueInt(), isFirstNum, isOperator, isSecondNum, secondNumberValue, sequence, SetOperator(), and WaitSomeTime().
Referenced by OnTriggerEnter().
        {
                //display current numbers and operator
                if(i == 1 && sequence == 1){
                        isFirstNum = true;
                        firstNumberValue = GetValueInt(s);
                }else if(i == 2 && sequence == 2){
                        isOperator = true;
                        SetOperator (s);
                }else if(i == 3 && sequence == 3){
                        isSecondNum = true;
                        secondNumberValue = GetValueInt(s);
                        audio.PlayOneShot (calculateSound);
                        StartCoroutine(WaitSomeTime());
                }
        }
void PlayerGUI.DisplayCurrentComponents () [private]
this method display current numbers and operators
Definition at line 55 of file PlayerGUI.cs.
References carryingFlashLight, CDTimer, firstNumberValue, flashLight, gameLogic, GetOperatorValue(), GameLogic.GetTargetNumber(), isFirstNum, isOperator, isSecondNum, IsWinner(), labelTargetHeight, labelTargetWidth, labelTargetX, labelTargetY, popup, CountDownTimer.ResetTimer(), secondNumberValue, and winSound.
Referenced by OnGUI().
{
                GUIStyle opStyle = new GUIStyle(GUI.skin.label);
                GUIStyle numStyle = new GUIStyle(GUI.skin.label);
                GUIStyle targetStyle = new GUIStyle(GUI.skin.label);
                numStyle.fontSize = 50;
                opStyle.fontSize = 50;
                targetStyle.fontSize = 24;
                numStyle.normal.textColor = Color.red;
                opStyle.normal.textColor = Color.blue;
                targetStyle.normal.textColor = Color.green;
                GUI.Label (new Rect (0, 0, 75, 52),"First Number");
                Rect firstNumPosition = new Rect (0,21,75,52);
                GUI.Label (new Rect (130,0,52,52),"Operator");
                Rect operatorPosition = new Rect (130,21,42,52);
                GUI.Label (new Rect (267,0,95,52),"Second Number");
                Rect secondNumPosition = new Rect (267,21,75,52);
                GUI.Label (new Rect (labelTargetY, labelTargetX, labelTargetWidth, labelTargetHeight),"Target Number: "+gameLogic.GetTargetNumber (),targetStyle);
                GUILayout.BeginHorizontal ();
                if (isFirstNum) {
                        string s =  firstNumberValue.ToString();
                        GUI.Label(firstNumPosition, s , numStyle);
                }
                if (isOperator){
                        GUI.Label(operatorPosition , GetOperatorValue (), opStyle );
                }
                if (isSecondNum){
                        string s = secondNumberValue.ToString();
                        GUI.Label (secondNumPosition, s, numStyle);
                }
                GUILayout.EndHorizontal ();
                if (carryingFlashLight){
                        GUI.Label (new Rect(Screen.width - 64,Screen.height - 64,64,64), flashLight);
                }
                if(IsWinner()){
                        //Laod next level.
                        audio.PlayOneShot(winSound);
                        popup.guiText.enabled = true;
                        CDTimer.ResetTimer(10000);
                }
        }
string PlayerGUI.GetOperatorValue () [private]
This method (getter) return the current operatorValue return String value of the Operator
Definition at line 247 of file PlayerGUI.cs.
References operatorValue.
Referenced by Calculate(), and DisplayCurrentComponents().
{ return operatorValue; }
int PlayerGUI.GetValueInt (string s) [private]
This method (getter) translates the value of Number from String to Int
Parameters:
s String value to be translated to Int
Returns:
int The translation from String to Int
Definition at line 223 of file PlayerGUI.cs.
Referenced by ComponentsToDisplay().
{
                        if (s == "1"){return 1;}
                else if(s == "2"){return 2;}
                else if(s == "3"){return 3;}
                else if(s == "4"){return 4;}
                else if(s == "5"){return 5;}
                else if(s == "6"){return 6;}
                else if(s == "7"){return 7;}
                else if(s == "8"){return 8;}
                else if(s == "9"){return 9;}
                                        else {return 10;}
        }
void PlayerGUI.IncreaseSequence () [private]
A method to increase the sequence of the equation: 1: first number. 2: operator. 3: second number
Parameters:
sequence Int represents what object need to be picked up (Operator or a Number)
Definition at line 212 of file PlayerGUI.cs.
References sequence.
Referenced by OnTriggerEnter().
{
                        if (sequence < 3) { sequence ++; }
                                                 else { sequence = 1;}
                }
bool PlayerGUI.IsCarryingFlashLight ()
This method confirms if the player is carrying a flash light or not
Returns:
bool (true: if the flash light was picked up)
Parameters:
carryingFlashLight bool
Definition at line 254 of file PlayerGUI.cs.
References carryingFlashLight.
{       return carryingFlashLight;      }
bool PlayerGUI.IsCarryingKey ()
This method determin if flash light is available or not
Returns:
bool (true: if player have flash light)
Definition at line 45 of file PlayerGUI.cs.
{return false;}
bool PlayerGUI.IsLoadedLevel (int i) [private]
Method used to determin the current loaded level
Parameters:
i Int argument (the number of level)
Returns:
bool (true: if i is the current loaded level)
Definition at line 308 of file PlayerGUI.cs.
Referenced by OnTriggerEnter().
{
                if( Application.loadedLevel == i){
                        return true;
                }else{
                        return false;
                }
        }
bool PlayerGUI.IsNumber (string s) [private]
This method is used to confirm any String is a Number or not
See also:
IsOperator()
Parameters:
s String to be checked
Returns:
bool (true: if the String passed is a Number)
Definition at line 274 of file PlayerGUI.cs.
Referenced by OnTriggerEnter().
{
                if (s == "+") { return false;
                } else if (s == "X") { return false;
                } else if (s == "-") { return false;
                } else if (s == "FlashLight") { return false;
                } else { return true; }
        }
bool PlayerGUI.IsOperator (string s) [private]
This method is used to check if a String is an Operator or not
See also:
IsNumber()
Parameters:
s String to be checked
Returns:
bool (true: if the String passed is an Operator)
Definition at line 262 of file PlayerGUI.cs.
Referenced by OnTriggerEnter().
{
                        if (s == "+") { return true;
                } else if (s == "X") { return true;
                } else if (s == "-") { return true;
                } else { return false; }
        }
bool PlayerGUI.IsWinner () [private]
This method checks the condition of win
Returns:
bool (true: if
See also:
targetNumber is equal calculation result
firstNumberValue)
Definition at line 104 of file PlayerGUI.cs.
References firstNumberValue, gameLogic, and GameLogic.GetTargetNumber().
Referenced by DisplayCurrentComponents().
{
                int targetNumber = gameLogic.GetTargetNumber ();
                if(firstNumberValue == targetNumber ){
                        return true;
                }else{ return false;}
        }
void PlayerGUI.OnGUI () [private]
This method is called on every frame refreshed
Definition at line 48 of file PlayerGUI.cs.
References DisplayCurrentComponents().
        {
                DisplayCurrentComponents ();
        }
void PlayerGUI.OnTriggerEnter (Collider c) [private]
This method is triggered when the player enters any colliders objects on the level
Parameters:
c the objects collider
tag String tag value of the collided object
See also:
IsNumber()
ComponentsToDisplay()
IncreaseSequence()
IsLoadedLevel()
ShowOperators
ShowNumbers()
ShowOperators()
TurnFlashLightOn()
Definition at line 170 of file PlayerGUI.cs.
References carryingFlashLight, ComponentsToDisplay(), errorSound, flashLightOn, IncreaseSequence(), IsLoadedLevel(), IsNumber(), IsOperator(), numbersGO, numberSound, operatorSound, sequence, ShowNumbers(), ShowOperators(), and TurnFlashLightOn().
        {
                string tag = c.tag;
                if (IsNumber (tag) && sequence != 2) {
                        ComponentsToDisplay (tag, sequence);
                        audio.PlayOneShot (numberSound);
                        IncreaseSequence ();
                        if(IsLoadedLevel(5)){
                                ShowOperators();
                        }
                } else if (IsOperator (tag) && sequence == 2) {
                        ComponentsToDisplay (tag, sequence);
                        audio.PlayOneShot (operatorSound);
                        IncreaseSequence ();
                        if(IsLoadedLevel(5)){
                                ShowNumbers();
                        }
                } else if (tag == "FlashLight") {
                        if(IsLoadedLevel(4)){
                                numbersGO.SetActive(true);
                                operatorsGO.SetActive(true);
                        }
                        if(IsLoadedLevel(5)){
                                ShowNumbers();
                        }
                        carryingFlashLight = true;
                        audio.PlayOneShot (flashLightOn);
                        TurnFlashLightOn();
                } else {
                        audio.PlayOneShot(errorSound);
                }
        }
void PlayerGUI.SetOperator (string s) [private]
This method (setter) sets the value OperatorValue to the String passed
Parameters:
s String will be the value of the Operator
See also:
GetOperatorValue()
Definition at line 241 of file PlayerGUI.cs.
References operatorValue.
Referenced by ComponentsToDisplay().
{ operatorValue = s; }
void PlayerGUI.ShowNumbers () [private]
This method is used to show grouped GameObject Numbers and hide Operators
See also:
ShowOperators()
Definition at line 291 of file PlayerGUI.cs.
References numbersGO.
Referenced by OnTriggerEnter().
{
                numbersGO.SetActive (true);
                operatorsGO.SetActive (false);
        }
void PlayerGUI.ShowOperators () [private]
This method is used to hide grouped GameObject Numbers and show Operators
See also:
ShowNumbers()
Definition at line 299 of file PlayerGUI.cs.
References numbersGO.
Referenced by OnTriggerEnter().
{
                numbersGO.SetActive (false);
                operatorsGO.SetActive (true);
        }
void PlayerGUI.TurnFlashLightOn () [private]
this method will turn the flashlight on
Definition at line 282 of file PlayerGUI.cs.
References carryingFlashLight, and spotlightGO.
Referenced by OnTriggerEnter().
        {
                carryingFlashLight = true;
                spotlightGO.SetActive (true);
        }
IEnumerator PlayerGUI.WaitSomeTime () [private]
This method when called will wait for 2 seconds then call the method
See also:
Calculate()
Parameters:
timeToWait float value of the time to wait
Definition at line 139 of file PlayerGUI.cs.
References Calculate().
Referenced by ComponentsToDisplay().
{
                float timeToWait = 2f;
                yield return new WaitForSeconds(timeToWait); // waits 2 seconds
            Calculate ();
    }
Member Data Documentation
AudioClip PlayerGUI.calculateSound
Definition at line 23 of file PlayerGUI.cs.
Referenced by ComponentsToDisplay().
bool PlayerGUI.carryingFlashLight = false [private]
Definition at line 32 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents(), IsCarryingFlashLight(), OnTriggerEnter(), and TurnFlashLightOn().
CountDownTimer PlayerGUI.CDTimer
Definition at line 16 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents().
AudioClip PlayerGUI.errorSound
Definition at line 25 of file PlayerGUI.cs.
Referenced by OnTriggerEnter().
int PlayerGUI.firstNumberValue [private]
Definition at line 34 of file PlayerGUI.cs.
Referenced by Calculate(), ComponentsToDisplay(), DisplayCurrentComponents(), and IsWinner().
Texture2D PlayerGUI.flashLight
Definition at line 20 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents().
AudioClip PlayerGUI.flashLightOn
Definition at line 24 of file PlayerGUI.cs.
Referenced by OnTriggerEnter().
GameLogic PlayerGUI.gameLogic
Definition at line 15 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents(), and IsWinner().
bool PlayerGUI.isFirstNum [private]
Definition at line 29 of file PlayerGUI.cs.
Referenced by ComponentsToDisplay(), and DisplayCurrentComponents().
bool PlayerGUI.isOperator [private]
Definition at line 31 of file PlayerGUI.cs.
Referenced by Calculate(), ComponentsToDisplay(), and DisplayCurrentComponents().
bool PlayerGUI.isSecondNum [private]
Definition at line 30 of file PlayerGUI.cs.
Referenced by Calculate(), ComponentsToDisplay(), and DisplayCurrentComponents().
int PlayerGUI.labelTargetHeight = 100 [private]
Definition at line 40 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents().
int PlayerGUI.labelTargetWidth = 400 [private]
Definition at line 39 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents().
int PlayerGUI.labelTargetX = Screen.height - 100 [private]
Definition at line 38 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents().
int PlayerGUI.labelTargetY = Screen.width / 2 - 100 [private]
Definition at line 37 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents().
GameObject PlayerGUI.numbersGO
Definition at line 18 of file PlayerGUI.cs.
Referenced by OnTriggerEnter(), ShowNumbers(), and ShowOperators().
AudioClip PlayerGUI.numberSound
Definition at line 21 of file PlayerGUI.cs.
Referenced by OnTriggerEnter().
GameObject PlayerGUI.operatorsGO
Definition at line 19 of file PlayerGUI.cs.
AudioClip PlayerGUI.operatorSound
Definition at line 22 of file PlayerGUI.cs.
Referenced by OnTriggerEnter().
string PlayerGUI.operatorValue [private]
Definition at line 36 of file PlayerGUI.cs.
Referenced by GetOperatorValue(), and SetOperator().
GUIText PlayerGUI.popup
Definition at line 27 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents().
int PlayerGUI.result [private]
Definition at line 33 of file PlayerGUI.cs.
Referenced by Calculate().
int PlayerGUI.secondNumberValue [private]
Definition at line 35 of file PlayerGUI.cs.
Referenced by Calculate(), ComponentsToDisplay(), and DisplayCurrentComponents().
int PlayerGUI.sequence = 1 [private]
int value of equation sequence
Definition at line 28 of file PlayerGUI.cs.
Referenced by Calculate(), ComponentsToDisplay(), IncreaseSequence(), and OnTriggerEnter().
GameObject PlayerGUI.spotlightGO
Definition at line 17 of file PlayerGUI.cs.
Referenced by TurnFlashLightOn().
AudioClip PlayerGUI.winSound
Definition at line 26 of file PlayerGUI.cs.
Referenced by DisplayCurrentComponents().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/PlayerGUI.cs