Interactive Multimedia: GameLogic Class Reference
GameLogic Class Reference
Public Member Functions
int GetTargetNumber ()
Public Attributes
int minRange = 1
int maxRange = 10
Private Member Functions
void Start ()
void GenerateRandom ()
Private Attributes
int targetNumber
Detailed Description
Definition at line 7 of file GameLogic.cs.
Member Function Documentation
void GameLogic.GenerateRandom () [private]
This method generate a random number between
See also:
minRange and
maxRange and set the generated number to
targetNumber
GetTargetNumber()
Definition at line 20 of file GameLogic.cs.
References maxRange, minRange, and targetNumber.
Referenced by Start().
{
                targetNumber = UnityEngine.Random.Range(minRange, maxRange);
        }
int GameLogic.GetTargetNumber ()
This method (getter) returns the value of target number
See also:
targetNumber
Returns:
targetnumber
See also:
targetNumber
Definition at line 25 of file GameLogic.cs.
References targetNumber.
Referenced by PlayerGUI.DisplayCurrentComponents(), and PlayerGUI.IsWinner().
{
                return targetNumber;
        }
void GameLogic.Start () [private]
Definition at line 12 of file GameLogic.cs.
References GenerateRandom().
{
                GenerateRandom ();
        }
Member Data Documentation
int GameLogic.maxRange = 10
int maximum range
Definition at line 9 of file GameLogic.cs.
Referenced by GenerateRandom().
int GameLogic.minRange = 1
int minimum range
Definition at line 8 of file GameLogic.cs.
Referenced by GenerateRandom().
int GameLogic.targetNumber [private]
int Number to be achieved with equations to win level
Definition at line 10 of file GameLogic.cs.
Referenced by GenerateRandom(), and GetTargetNumber().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/GameLogic.cs